-- =============================================================
-- BakeryCostCalculator - V1: schema inicial
-- PostgreSQL (ver docs/DATABASE_SCHEMA.md)
-- =============================================================

-- Tabla de referencia: unidades de medida (ids fijos, corresponden al enum Java)
CREATE TABLE units_of_measurement (
    id SMALLINT NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- Insumos / materia prima
CREATE TABLE inputs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    price NUMERIC(10, 2) NOT NULL,
    unit_of_measurement_id SMALLINT NOT NULL REFERENCES units_of_measurement(id)
);

-- Recetas (con rendimiento persistido)
CREATE TABLE recipes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    yield_quantity NUMERIC(10, 4) NOT NULL,
    yield_unit_id SMALLINT NOT NULL REFERENCES units_of_measurement(id)
);

-- Ingredientes (composición receta-insumo; entidad débil)
CREATE TABLE ingredients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    input_id INTEGER NOT NULL REFERENCES inputs(id),
    quantity NUMERIC(10, 4) NOT NULL,
    UNIQUE (recipe_id, input_id)
);

-- Productos (precio manual opcional + override de margen)
CREATE TABLE products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    price NUMERIC(10, 2),
    target_margin NUMERIC(5, 4),
    recipe_id INTEGER NOT NULL REFERENCES recipes(id)
);

-- Costos fijos mensuales itemizados (F)
CREATE TABLE fixed_costs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    monthly_amount NUMERIC(12, 2) NOT NULL
);

-- Mano de obra mensual itemizada (L)
CREATE TABLE employees (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    monthly_salary NUMERIC(12, 2) NOT NULL,
    monthly_hours NUMERIC(7, 2)
);

-- Configuración global de costeo (singleton)
CREATE TABLE cost_settings (
    id SMALLINT NOT NULL PRIMARY KEY DEFAULT 1,
    default_target_margin NUMERIC(5, 4) NOT NULL,
    monthly_material_base NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'ARS',
    CONSTRAINT cost_settings_singleton CHECK (id = 1)
);

-- =============================================================
-- Seeds
-- =============================================================
INSERT INTO units_of_measurement (id, name) VALUES
    (1, 'KILOGRAM'),
    (2, 'GRAM'),
    (3, 'MILLIGRAM'),
    (4, 'LITER'),
    (5, 'MILLILITER'),
    (6, 'UNIT');

-- Valores iniciales de costeo: ajustar desde la app antes de costear
-- (monthly_material_base en 1.00 como placeholder; el negocio debe configurarlo)
INSERT INTO cost_settings (id, default_target_margin, monthly_material_base, currency) VALUES
    (1, 0.3500, 1.00, 'ARS');
