-- =============================================================
-- BakeryCostCalculator (Bready) - V2: usuarios + multi-tenancy
-- Cada usuario es dueño de sus insumos, recetas, productos,
-- costos fijos, empleados y su configuración de costeo.
-- =============================================================

-- Usuarios
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    photo BYTEA,
    photo_content_type VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

-- -------------------------------------------------------------
-- Limpieza de datos "sin dueño" (entorno dev, sin datos productivos).
-- Debe respetar el orden de FKs.
-- -------------------------------------------------------------
DELETE FROM ingredients;
DELETE FROM products;
DELETE FROM recipes;
DELETE FROM inputs;
DELETE FROM fixed_costs;
DELETE FROM employees;

-- -------------------------------------------------------------
-- inputs: dueño + unique por usuario
-- -------------------------------------------------------------
ALTER TABLE inputs DROP CONSTRAINT IF EXISTS inputs_name_key;
ALTER TABLE inputs ADD COLUMN user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE inputs ADD CONSTRAINT inputs_name_user_unique UNIQUE (user_id, name);

-- -------------------------------------------------------------
-- recipes: dueño + unique por usuario
-- -------------------------------------------------------------
ALTER TABLE recipes DROP CONSTRAINT IF EXISTS recipes_name_key;
ALTER TABLE recipes ADD COLUMN user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE recipes ADD CONSTRAINT recipes_name_user_unique UNIQUE (user_id, name);

-- -------------------------------------------------------------
-- products: dueño + unique por usuario
-- -------------------------------------------------------------
ALTER TABLE products DROP CONSTRAINT IF EXISTS products_name_key;
ALTER TABLE products ADD COLUMN user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE products ADD CONSTRAINT products_name_user_unique UNIQUE (user_id, name);

-- -------------------------------------------------------------
-- fixed_costs: dueño + unique por usuario
-- -------------------------------------------------------------
ALTER TABLE fixed_costs DROP CONSTRAINT IF EXISTS fixed_costs_name_key;
ALTER TABLE fixed_costs ADD COLUMN user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE fixed_costs ADD CONSTRAINT fixed_costs_name_user_unique UNIQUE (user_id, name);

-- -------------------------------------------------------------
-- employees: dueño (sin unique de nombre; V1 no lo tenía)
-- -------------------------------------------------------------
ALTER TABLE employees ADD COLUMN user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE;

-- -------------------------------------------------------------
-- cost_settings: deja de ser singleton -> una fila por usuario.
-- Se recrea la tabla (el seed anterior era placeholder).
-- -------------------------------------------------------------
DROP TABLE cost_settings;
CREATE TABLE cost_settings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    default_target_margin NUMERIC(5, 4) NOT NULL,
    monthly_material_base NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'ARS'
);
