spring.datasource.url=jdbc:postgresql://localhost:5432/bakery_cost_calculator
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
server.port=8080
